modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="jeid"
version="${file.jarVersion}"
displayName="Just Enough Item Descriptions (JEID)"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="jeid.png"
#credits="Joe Mama"
authors="LegoMaster3650"
displayTest="MATCH_VERSION"
description='''
Yeah this is a mod it does stuff and things
'''

[[dependencies.jeid]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.jeid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.jeid]
	catalogueItemIcon="minecraft:paper"