modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/LegoMaster3650/JustEnoughItemDescriptions/issues"

[[mods]]
modId="jeidescs"
version="${file.jarVersion}"
displayName="Just Enough Item Descriptions (JEIDescs)"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jeidescs"
logoFile="jeidescs.png"
#credits="Joe Mama"
authors="LegoMaster3650"
displayTest="MATCH_VERSION"
description='''
JEI Item/Fluid descriptions in a simple JSON format
'''

[[dependencies.jeidescs]]
	modId="forge"
	mandatory=true
	versionRange="[44,)"
	ordering="NONE"
	side="BOTH"
	
[[dependencies.jeidescs]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.3,1.20)"
	ordering="NONE"
	side="BOTH"

[[dependencies.jeidescs]]
	modId="jei"
	mandatory=true
	versionRange="[12,)"
	ordering="NONE"
	side="BOTH"

[modproperties.jeidescs]
	catalogueItemIcon="minecraft:paper"